const ERROR_CODE = 400;
const NOT_FOUND_CODE = 404;
const CREATED_CODE = 201;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  ERROR_CODE,
  NOT_FOUND_CODE,
  CREATED_CODE,
  INTERNAL_SERVER_ERROR,
};
